In [1]:
import os
import time

import numpy as np
import pandas as pd

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

In [2]:
pd.set_option('display.height', 1000)
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [3]:
data_dir = 'resources'
file_name = 'Task_scoring_modeller_Nov2016.xlsx'

file_path = os.path.join(data_dir, file_name)

In [4]:
df = pd.read_excel(file_path, sheet_name='Data', index_col='client_id')

In [5]:
df.shape

(32144, 38)

In [6]:
df.head(10)

                 status mobile_operator  gender    email_domain  application_hour  application_day  application_weekday  asked_amount  term application_type  client_age  registration_hour actual_city  reg_req_date_match  days_since_reg  accept_news  email_contains_dob bank  monthly_income  monthly_liabilities              work_status  p1m_req_cnt  p6m_req_cnt  loans_taken_p6m  loans_taken_p12m  sum_loans_taken_p6m  sum_loans_taken_p12m  sum_contract_amount  max_contract_amount  avg_contract_amount  sum_ConsumerLoan  days_since_most_recent_cr_start  days_since_first_cr_start  ci_p1m_req_count  ci_p3m_req_count  ci_p6m_req_count  closed_credits_count  open_credits_count
client_id
1                  GOOD          LaiLai    MALE     hotmail.com                12                9                    1           500  30.0            Type1          30                 12     თბილისი                   1               0          1.0                   0   BG           500.0                500.0                  Working          0.0            0              1.0               1.0                  0.0                   0.0                  0.0                  0.0                  0.0               0.0                             15.0                       15.0               0.0               4.0               4.0                   0.0                 1.0
2                  GOOD         Beeline    MALE         mail.ru                12                7                    3           300  30.0            Type1          29                 10  ახალქალაქი                   0              34          1.0                   0   BG           900.0                  0.0  Individual entrepreneur          3.0            4              1.0               1.0                300.0                 300.0                250.0                250.0                250.0             250.0                             23.0                       23.0               0.0               3.0               3.0                   0.0                 1.0
3                  GOOD            Bali  FEMALE       gmail.com                20               29                    0           200  30.0            Type1          20                 20       კასპი                   1               0          1.0                   0   BG           300.0                100.0                  Working          0.0            0              1.0               1.0                100.0                 100.0                100.0                100.0                100.0             100.0                             26.0                       26.0               0.0               1.0               2.0                   0.0                 1.0
4                  GOOD          LaiLai  FEMALE         mail.ru                11               11                    4           500  30.0            Type1          36                 19     რუსთავი                   0              42          1.0                   0   BG           500.0                  0.0                  Working          0.0            1              1.0               1.0                300.0                 300.0                250.0                250.0                250.0             250.0                             26.0                       26.0               0.0               2.0               2.0                   0.0                 1.0
5                  GOOD         Beeline  FEMALE         mail.ru                13                8                    4           250  30.0            Type1          53                 13   ზესტაფონი                   0              42          1.0                   1   LB           500.0                  0.0     Self-employed person          0.0            1              1.0               1.0                300.0                 300.0                250.0                250.0                250.0             250.0                             28.0                       28.0               0.0               2.0               2.0                   0.0                 1.0
6                  GOOD        Magticom  FEMALE  iliauni.edu.ge                14               25                    4           250  30.0            Type1          20                 14     თბილისი                   1               0          1.0                   0   BG           300.0                 50.0                  Working          0.0            0              1.0               1.0                100.0                 100.0                100.0                100.0                100.0             100.0                             29.0                       29.0               0.0               1.0               2.0                   0.0                 1.0
7                  GOOD          LaiLai    MALE       gmail.com                12                7                    0           500  30.0            Type1          21                 12     თბილისი                   1               0          1.0                   0   TB           900.0                  0.0                  Working          0.0            0              1.0               1.0                100.0                 100.0                100.0                100.0                100.0             100.0                             29.0                       29.0               0.0               1.0               1.0                   0.0                 1.0
8          INDETERMINED            Bali    MALE         mail.ru                14                3                    3           100  30.0            Type1          20                 14     თბილისი                   1               0          1.0                   0   BG           300.0                 50.0                  Working          0.0            0              1.0               1.0                100.0                 100.0                100.0                100.0                100.0             100.0                             29.0                       29.0               0.0               1.0               1.0                   0.0                 1.0
9                  GOOD        Magticom  FEMALE           bk.ru                15               22                    1           300  30.0            Type2          23                 12     თბილისი                   0              29          1.0                   1   TB           100.0                350.0                  Working          1.0            1              1.0               1.0                200.0                 200.0                200.0                200.0                200.0             200.0                             29.0                       29.0               0.0               1.0               1.0                   0.0                 1.0
10                 GOOD        Magticom    MALE       yahoo.com                19               16                    2           500  30.0            Type1          48                 19     თბილისი                   1               0          1.0                   0   TB           700.0                  0.0  Individual entrepreneur          0.0            0              1.0               1.0                300.0                 300.0                250.0                250.0                250.0             250.0                             29.0                       29.0               0.0               1.0               3.0                   1.0                 1.0

In [7]:
df['status'].unique()

array(['GOOD', 'INDETERMINED', 'BAD'], dtype=object)

In [8]:
df = df[df['status'] != 'INDETERMINED']

In [9]:
df['status'] = df.apply(lambda row: 1 if row['status'] == 'GOOD' else 0, axis=1)

In [10]:
df.shape

(31439, 38)

In [11]:
def calc_summary(df):
    return pd.DataFrame(
        data=np.array([df.dtypes, df.nunique(), df.isna().sum()]).T, 
        columns=['dtype', 'nunique', 'nan_count'], 
        index=df.columns
    )

In [12]:
calc_summary(df)

                                   dtype nunique nan_count
status                             int64       2         0
mobile_operator                   object      10         1
gender                            object       2         0
email_domain                      object     499         0
application_hour                   int64      24         0
application_day                    int64      31         0
application_weekday                int64       7         0
asked_amount                       int64      23         0
term                             float64      26         1
application_type                  object       4         0
client_age                         int64      46         0
registration_hour                  int64      24         0
actual_city                       object      90        35
reg_req_date_match                 int64       2         0
days_since_reg                     int64     761         0
accept_news                      float64       2         1
email_contains_dob                 int64       2         0
bank                              object      16         3
monthly_income                   float64      34       109
monthly_liabilities              float64      37      1430
work_status                       object      11       110
p1m_req_cnt                      float64      21         2
p6m_req_cnt                        int64      39         0
loans_taken_p6m                  float64      29         5
loans_taken_p12m                 float64      39        28
sum_loans_taken_p6m              float64     508        29
sum_loans_taken_p12m             float64     763        29
sum_contract_amount              float64    6053        30
max_contract_amount              float64    1888        30
avg_contract_amount              float64    1374        29
sum_ConsumerLoan                 float64    4592         6
days_since_most_recent_cr_start  float64    1927        28
days_since_first_cr_start        float64    3311        28
ci_p1m_req_count                 float64      38         7
ci_p3m_req_count                 float64      76         5
ci_p6m_req_count                 float64     103         5
closed_credits_count             float64      70         5
open_credits_count               float64      19         6

In [13]:
df.dropna(inplace=True)

In [14]:
df.shape

(29915, 38)

In [15]:
def make_abs_freq_dict(items):
    return {x: items.count(x) for x in set(items)}


def make_rel_freq_dict(items):
    abs_freq_dict = make_abs_freq_dict(items)
    values_total = sum(abs_freq_dict.values())
    return {item: abs_freq / values_total for item, abs_freq in abs_freq_dict.items()}

In [16]:
def list_rare_values(items, threshold=0.01):
    rel_freq_dict = make_rel_freq_dict(items)
    return [item for item, rel_freq in rel_freq_dict.items() if rel_freq < threshold]

In [17]:
rare_mobile_operators = set(list_rare_values(df['mobile_operator'].tolist()))
rare_mobile_operators

{'Silknet', 'Unknown operator', 'Wrong length', 'Wrong mobile'}

In [18]:
rare_email_domains = set(list_rare_values(df['email_domain'].tolist()))
len(rare_email_domains)

477

In [19]:
rare_actual_cities = set(list_rare_values(df['actual_city'].tolist()))
len(rare_actual_cities)

71

In [20]:
rare_banks = set(list_rare_values(df['bank'].tolist()))
rare_banks

{'BS', 'BT', 'CR', 'CS', 'FG', 'HB', 'IN', 'KS', 'PC', 'PG', 'VT', 'ZB'}

In [21]:
make_abs_freq_dict(df['work_status'].tolist())

{'Individual entrepreneur': 1513,
 'Pensioner': 137,
 'Self-employed person': 5014,
 'Social beneficiaries': 92,
 'Student': 278,
 'Unemployed': 186,
 'Working': 22693,
 'შპს ფასანაური': 1,
 'შპს ჯეკა გრუპი / გასართობი ცენტრი ბუმბული': 1}

In [22]:
df = df[~df['work_status'].isin({'შპს ფასანაური', 'შპს ჯეკა გრუპი / გასართობი ცენტრი ბუმბული'})]

In [23]:
def replace_rare_values(value, rare_values, default_value='RARE'):
    return default_value if value in rare_values else value


def replace_rare_mobile_operators(value, default_value='RARE'):
    return replace_rare_values(value, rare_mobile_operators, default_value=default_value)


def replace_rare_email_domains(value, default_value='RARE'):
    return replace_rare_values(value, rare_email_domains, default_value=default_value)


def replace_rare_actual_cities(value, default_value='RARE'):
    return replace_rare_values(value, rare_actual_cities, default_value=default_value)


def replace_rare_banks(value, default_value='RARE'):
    return replace_rare_values(value, rare_banks, default_value=default_value)

In [24]:
df['mobile_operator'] = df.apply(lambda row: replace_rare_mobile_operators(row['mobile_operator']), axis=1)
df['email_domain'] = df.apply(lambda row: replace_rare_email_domains(row['email_domain']), axis=1)
df['actual_city'] = df.apply(lambda row: replace_rare_actual_cities(row['actual_city']), axis=1)
df['bank'] = df.apply(lambda row: replace_rare_banks(row['bank']), axis=1)

In [25]:
calc_summary(df)

                                   dtype nunique nan_count
status                             int64       2         0
mobile_operator                   object       7         0
gender                            object       2         0
email_domain                      object       8         0
application_hour                   int64      24         0
application_day                    int64      31         0
application_weekday                int64       7         0
asked_amount                       int64      22         0
term                             float64      26         0
application_type                  object       4         0
client_age                         int64      46         0
registration_hour                  int64      24         0
actual_city                       object      18         0
reg_req_date_match                 int64       2         0
days_since_reg                     int64     540         0
accept_news                      float64       2         0
email_contains_dob                 int64       2         0
bank                              object       5         0
monthly_income                   float64      30         0
monthly_liabilities              float64      35         0
work_status                       object       7         0
p1m_req_cnt                      float64      20         0
p6m_req_cnt                        int64      36         0
loans_taken_p6m                  float64      27         0
loans_taken_p12m                 float64      37         0
sum_loans_taken_p6m              float64     495         0
sum_loans_taken_p12m             float64     742         0
sum_contract_amount              float64    5891         0
max_contract_amount              float64    1853         0
avg_contract_amount              float64    1358         0
sum_ConsumerLoan                 float64    4445         0
days_since_most_recent_cr_start  float64    1879         0
days_since_first_cr_start        float64    3285         0
ci_p1m_req_count                 float64      37         0
ci_p3m_req_count                 float64      69         0
ci_p6m_req_count                 float64      90         0
closed_credits_count             float64      66         0
open_credits_count               float64      19         0

In [26]:
categorical_columns = [
    'mobile_operator', 'gender', 'email_domain', 'application_weekday', 'application_type', 'registration_hour', 'actual_city',
    'bank', 'work_status'
]

df = pd.get_dummies(
    data=df, prefix_sep='__', 
    columns=categorical_columns,
    drop_first=True
)

In [27]:
df.shape

(29913, 102)

In [28]:
df.head()

,status,application_hour,application_day,asked_amount,term,client_age,reg_req_date_match,days_since_reg,accept_news,email_contains_dob,monthly_income,monthly_liabilities,p1m_req_cnt,p6m_req_cnt,loans_taken_p6m,loans_taken_p12m,sum_loans_taken_p6m,sum_loans_taken_p12m,sum_contract_amount,max_contract_amount,avg_contract_amount,sum_ConsumerLoan,days_since_most_recent_cr_start,days_since_first_cr_start,ci_p1m_req_count,ci_p3m_req_count,ci_p6m_req_count,closed_credits_count,open_credits_count,mobile_operator__Bani,mobile_operator__Beeline,mobile_operator__Geocell,mobile_operator__LaiLai,mobile_operator__Magticom,mobile_operator__RARE,gender__MALE,email_domain__bk.ru,email_domain__gmail.com,email_domain__inbox.ru,email_domain__list.ru,email_domain__mail.ru,email_domain__rambler.ru,email_domain__yahoo.com,application_weekday__1,application_weekday__2,application_weekday__3,application_weekday__4,application_weekday__5,application_weekday__6,application_type__Type2,application_type__Type3,application_type__Type4,registration_hour__1,registration_hour__2,registration_hour__3,registration_hour__4,registration_hour__5,registration_hour__6,registration_hour__7,registration_hour__8,registration_hour__9,registration_hour__10,registration_hour__11,registration_hour__12,registration_hour__13,registration_hour__14,registration_hour__15,registration_hour__16,registration_hour__17,registration_hour__18,registration_hour__19,registration_hour__20,registration_hour__21,registration_hour__22,registration_hour__23,actual_city__ახალციხე,actual_city__ბათუმი,actual_city__გორი,actual_city__გურჯაანი,actual_city__ზესტაფონი,actual_city__ზუგდიდი,actual_city__თბილისი,actual_city__თელავი,actual_city__ოზურგეთი,actual_city__რუსთავი,actual_city__სამტრედია,actual_city__სენაკი,actual_city__სხვა,actual_city__ფოთი,actual_city__ქობულეთი,actual_city__ქუთაისი,actual_city__ხაშური,bank__BR,bank__LB,bank__RARE,bank__TB,work_status__Pensioner,work_status__Self-employed person,work_status__Social beneficiaries,work_status__Student,work_status__Unemployed,work_status__Working
client_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,1,12,9,500,30.0,30,1,0,1.0,0,500.0,500.0,0.0,0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0,15.0,0.0,4.0,4.0,0.0,1.0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
2,1,12,7,300,30.0,29,0,34,1.0,0,900.0,0.0,3.0,4,1.0,1.0,300.0,300.0,250.0,250.0,250.0,250.0,23.0,23.0,0.0,3.0,3.0,0.0,1.0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,1,20,29,200,30.0,20,1,0,1.0,0,300.0,100.0,0.0,0,1.0,1.0,100.0,100.0,100.0,100.0,100.0,100.0,26.0,26.0,0.0,1.0,2.0,0.0,1.0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
4,1,11,11,500,30.0,36,0,42,1.0,0,500.0,0.0,0.0,1,1.0,1.0,300.0,300.0,250.0,250.0,250.0,250.0,26.0,26.0,0.0,2.0,2.0,0.0,1.0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
5,1,13,8,250,30.0,53,0,42,1.0,1,500.0,0.0,0.0,1,1.0,1.0,300.0,300.0,250.0,250.0,250.0,250.0,28.0,28.0,0.0,2.0,2.0,0.0,1.0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0

In [29]:
calc_summary(df)

                                     dtype nunique nan_count
status                               int64       2         0
application_hour                     int64      24         0
application_day                      int64      31         0
asked_amount                         int64      22         0
term                               float64      26         0
client_age                           int64      46         0
reg_req_date_match                   int64       2         0
days_since_reg                       int64     540         0
accept_news                        float64       2         0
email_contains_dob                   int64       2         0
monthly_income                     float64      30         0
monthly_liabilities                float64      35         0
p1m_req_cnt                        float64      20         0
p6m_req_cnt                          int64      36         0
loans_taken_p6m                    float64      27         0
loans_taken_p12m                   float64      37         0
sum_loans_taken_p6m                float64     495         0
sum_loans_taken_p12m               float64     742         0
sum_contract_amount                float64    5891         0
max_contract_amount                float64    1853         0
avg_contract_amount                float64    1358         0
sum_ConsumerLoan                   float64    4445         0
days_since_most_recent_cr_start    float64    1879         0
days_since_first_cr_start          float64    3285         0
ci_p1m_req_count                   float64      37         0
ci_p3m_req_count                   float64      69         0
ci_p6m_req_count                   float64      90         0
closed_credits_count               float64      66         0
open_credits_count                 float64      19         0
mobile_operator__Bani                uint8       2         0
mobile_operator__Beeline             uint8       2         0
mobile_operator__Geocell             uint8       2         0
mobile_operator__LaiLai              uint8       2         0
mobile_operator__Magticom            uint8       2         0
mobile_operator__RARE                uint8       2         0
gender__MALE                         uint8       2         0
email_domain__bk.ru                  uint8       2         0
email_domain__gmail.com              uint8       2         0
email_domain__inbox.ru               uint8       2         0
email_domain__list.ru                uint8       2         0
email_domain__mail.ru                uint8       2         0
email_domain__rambler.ru             uint8       2         0
email_domain__yahoo.com              uint8       2         0
application_weekday__1               uint8       2         0
application_weekday__2               uint8       2         0
application_weekday__3               uint8       2         0
application_weekday__4               uint8       2         0
application_weekday__5               uint8       2         0
application_weekday__6               uint8       2         0
application_type__Type2              uint8       2         0
application_type__Type3              uint8       2         0
application_type__Type4              uint8       2         0
registration_hour__1                 uint8       2         0
registration_hour__2                 uint8       2         0
registration_hour__3                 uint8       2         0
registration_hour__4                 uint8       2         0
registration_hour__5                 uint8       2         0
registration_hour__6                 uint8       2         0
registration_hour__7                 uint8       2         0
registration_hour__8                 uint8       2         0
registration_hour__9                 uint8       2         0
registration_hour__10                uint8       2         0
registration_hour__11                uint8       2         0
registration_hour__12                uint8       2         0
registration_hour__13                uint8       2         0
registration_hour__14                uint8       2         0
registration_hour__15                uint8       2         0
registration_hour__16                uint8       2         0
registration_hour__17                uint8       2         0
registration_hour__18                uint8       2         0
registration_hour__19                uint8       2         0
registration_hour__20                uint8       2         0
registration_hour__21                uint8       2         0
registration_hour__22                uint8       2         0
registration_hour__23                uint8       2         0
actual_city__ახალციხე                uint8       2         0
actual_city__ბათუმი                  uint8       2         0
actual_city__გორი                    uint8       2         0
actual_city__გურჯაანი                uint8       2         0
actual_city__ზესტაფონი               uint8       2         0
actual_city__ზუგდიდი                 uint8       2         0
actual_city__თბილისი                 uint8       2         0
actual_city__თელავი                  uint8       2         0
actual_city__ოზურგეთი                uint8       2         0
actual_city__რუსთავი                 uint8       2         0
actual_city__სამტრედია               uint8       2         0
actual_city__სენაკი                  uint8       2         0
actual_city__სხვა                    uint8       2         0
actual_city__ფოთი                    uint8       2         0
actual_city__ქობულეთი                uint8       2         0
actual_city__ქუთაისი                 uint8       2         0
actual_city__ხაშური                  uint8       2         0
bank__BR                             uint8       2         0
bank__LB                             uint8       2         0
bank__RARE                           uint8       2         0
bank__TB                             uint8       2         0
work_status__Pensioner               uint8       2         0
work_status__Self-employed person    uint8       2         0
work_status__Social beneficiaries    uint8       2         0
work_status__Student                 uint8       2         0
work_status__Unemployed              uint8       2         0
work_status__Working                 uint8       2         0

In [30]:
status_df = pd.DataFrame(data=df['status'], index=df.index)
df.drop(labels=['status'], axis=1, inplace=True)

In [31]:
numeric_columns = df.select_dtypes(include=[np.int64, np.float64]).columns.tolist()

In [32]:
df[numeric_columns] = MinMaxScaler().fit_transform(df[numeric_columns].values)

In [33]:
X = df.values
y = status_df.values

In [34]:
print(X.shape)
print(y.shape)

(29913, 101)
(29913, 1)

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=1)

In [36]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(26921, 101)
(2992, 101)
(26921, 1)
(2992, 1)

In [37]:
l2_penalty_powers = np.random.uniform(low=-7, high=-2, size=10)
l2_penalties = 10 ** l2_penalty_powers

In [38]:
for i, l2_penalty in enumerate(l2_penalties):
    print('#exp: {}'.format(i + 1))
    print('l2_penalty: {:.7f}'.format(l2_penalty))
    C = 1 / l2_penalty
    log_reg = LogisticRegression(solver='lbfgs', C=C, random_state=1).fit(X_train, y_train.ravel())
    y_pred = log_reg.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    print('accuracy: {:.4f}'.format(accuracy))
    print()

#exp: 1
l2_penalty: 0.0006491
accuracy: 0.8890

#exp: 2
l2_penalty: 0.0007987
accuracy: 0.8890

#exp: 3
l2_penalty: 0.0023091
accuracy: 0.8894

#exp: 4
l2_penalty: 0.0000012
accuracy: 0.8894

#exp: 5
l2_penalty: 0.0000015
accuracy: 0.8894

#exp: 6
l2_penalty: 0.0005495
accuracy: 0.8890

#exp: 7
l2_penalty: 0.0003154
accuracy: 0.8890

#exp: 8
l2_penalty: 0.0000013
accuracy: 0.8894

#exp: 9
l2_penalty: 0.0000097
accuracy: 0.8890

#exp: 10
l2_penalty: 0.0000002
accuracy: 0.8894

In [39]:
for i in range(11):
    print('#exp: {}'.format(i + 1))
    n_estimators = 100 + i * 10
    print('n_estimators: {}'.format(n_estimators))
    rf = RandomForestClassifier(
        n_estimators=n_estimators, max_depth=15, random_state=1
    ).fit(X_train, y_train.ravel())
    y_pred = rf.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    print('accuracy: {:.4f}'.format(accuracy))
    print()

#exp: 1
n_estimators: 100
accuracy: 0.8920

#exp: 2
n_estimators: 110
accuracy: 0.8924

#exp: 3
n_estimators: 120
accuracy: 0.8927

#exp: 4
n_estimators: 130
accuracy: 0.8924

#exp: 5
n_estimators: 140
accuracy: 0.8920

#exp: 6
n_estimators: 150
accuracy: 0.8920

#exp: 7
n_estimators: 160
accuracy: 0.8920

#exp: 8
n_estimators: 170
accuracy: 0.8920

#exp: 9
n_estimators: 180
accuracy: 0.8917

#exp: 10
n_estimators: 190
accuracy: 0.8917

#exp: 11
n_estimators: 200
accuracy: 0.8917

In [42]:
def prepare_nn_params(n_exp):
    
    layes_1_sizes = np.random.randint(low=2, high=100 + 1, size=n_exp)
    layes_2_sizes = np.random.randint(low=2, high=50 + 1, size=n_exp)
    layes_3_sizes = np.random.randint(low=2, high=40 + 1, size=n_exp)

    
    l2_penalty_powers = np.random.uniform(low=-7, high=-2, size=n_exp)
    l2_penalties = 10 ** l2_penalty_powers
    
    learning_rate_powers = np.random.uniform(low=-5, high=-2, size=n_exp)
    learning_rates = 10 ** learning_rate_powers
    
    batch_size_powers = np.random.randint(low=5, high=10 + 1, size=n_exp)
    batch_sizes = 2 ** batch_size_powers
    
    return {
        'layes_1_sizes': layes_1_sizes,
        'layes_2_sizes': layes_2_sizes,
        'layes_3_sizes': layes_3_sizes,
        'l2_penalties': l2_penalties,
        'learning_rates': learning_rates,
        'batch_sizes': batch_sizes
    }

In [43]:
n_exp = 100
nn_params = prepare_nn_params(n_exp)
start = time.time()
previous_end = start


for i in range(n_exp):
    print('#exp: {}'.format(i + 1))

    hidden_layer_sizes = (
        nn_params['layes_1_sizes'][i], 
        nn_params['layes_2_sizes'][i],
        nn_params['layes_3_sizes'][i]
    )
    alpha = nn_params['l2_penalties'][i]
    learning_rate_init = nn_params['learning_rates'][i]
    batch_size = nn_params['batch_sizes'][i]
    
    print('hidden_layer_sizes:', hidden_layer_sizes)
    print('alpha: {:.7f}'.format(alpha))
    print('learning_rate_init: {:.7f}'.format(learning_rate_init))
    print('batch_size:', batch_size)
    
    nn = MLPClassifier(
        hidden_layer_sizes=hidden_layer_sizes,
        alpha=alpha,
        learning_rate_init=learning_rate_init,
        batch_size=batch_size,
        random_state=1
    ).fit(X_train, y_train.ravel())
    
    print('iterations spent:', nn.n_iter_)
    
    end = time.time()
    print('time spent: {:.1f}'.format(end - previous_end))
    previous_end = end
    
    y_pred = nn.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    print('accuracy: {:.4f}'.format(accuracy))
    
    print()

#exp: 1
hidden_layer_sizes: (99, 15, 27)
alpha: 0.0000002
learning_rate_init: 0.0037985
batch_size: 32
iterations spent: 60
time spent: 57.7
accuracy: 0.8366

#exp: 2
hidden_layer_sizes: (12, 13, 36)
alpha: 0.0000002
learning_rate_init: 0.0000288
batch_size: 1024
iterations spent: 153
time spent: 13.5
accuracy: 0.8907

#exp: 3
hidden_layer_sizes: (89, 29, 10)
alpha: 0.0000014
learning_rate_init: 0.0010506
batch_size: 256
iterations spent: 93
time spent: 23.8
accuracy: 0.8493

#exp: 4
hidden_layer_sizes: (73, 11, 32)
alpha: 0.0010436
learning_rate_init: 0.0000831
batch_size: 32

d:\users\user\appdata\local\programs\python\python36\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:563: ConvergenceWarning: Stochastic Optimizer: Maximum iterations reached and the optimization hasn't converged yet.
  % (), ConvergenceWarning)

iterations spent: 200
time spent: 228.7
accuracy: 0.8610

#exp: 5
hidden_layer_sizes: (31, 36, 21)
alpha: 0.0006933
learning_rate_init: 0.0002724
batch_size: 64
iterations spent: 176
time spent: 94.5
accuracy: 0.8616

#exp: 6
hidden_layer_sizes: (30, 29, 9)
alpha: 0.0055111
learning_rate_init: 0.0000971
batch_size: 512
iterations spent: 200
time spent: 23.9
accuracy: 0.8894

#exp: 7
hidden_layer_sizes: (59, 23, 25)
alpha: 0.0001263
learning_rate_init: 0.0006810
batch_size: 128
iterations spent: 115
time spent: 32.9
accuracy: 0.8399

#exp: 8
hidden_layer_sizes: (18, 30, 5)
alpha: 0.0010351
learning_rate_init: 0.0006067
batch_size: 1024
iterations spent: 163
time spent: 14.2
accuracy: 0.8783

#exp: 9
hidden_layer_sizes: (34, 38, 11)
alpha: 0.0000135
learning_rate_init: 0.0005341
batch_size: 512
iterations spent: 146
time spent: 19.9
accuracy: 0.8676

#exp: 10
hidden_layer_sizes: (14, 11, 37)
alpha: 0.0079115
learning_rate_init: 0.0003360
batch_size: 1024
iterations spent: 142
time spent: 12.7
accuracy: 0.8870

#exp: 11
hidden_layer_sizes: (9, 48, 35)
alpha: 0.0000117
learning_rate_init: 0.0001455
batch_size: 512
iterations spent: 160
time spent: 20.7
accuracy: 0.8897

#exp: 12
hidden_layer_sizes: (23, 5, 14)
alpha: 0.0000005
learning_rate_init: 0.0000623
batch_size: 64
iterations spent: 200
time spent: 61.8
accuracy: 0.8884

#exp: 13
hidden_layer_sizes: (36, 8, 31)
alpha: 0.0018053
learning_rate_init: 0.0047167
batch_size: 256
iterations spent: 51
time spent: 9.6
accuracy: 0.8596

#exp: 14
hidden_layer_sizes: (63, 48, 10)
alpha: 0.0000152
learning_rate_init: 0.0010001
batch_size: 64
iterations spent: 78
time spent: 42.7
accuracy: 0.8232

#exp: 15
hidden_layer_sizes: (100, 10, 10)
alpha: 0.0000043
learning_rate_init: 0.0050012
batch_size: 256
iterations spent: 50
time spent: 12.7
accuracy: 0.8362

#exp: 16
hidden_layer_sizes: (18, 47, 22)
alpha: 0.0000516
learning_rate_init: 0.0005555
batch_size: 64
iterations spent: 181
time spent: 81.3
accuracy: 0.8583

#exp: 17
hidden_layer_sizes: (78, 42, 38)
alpha: 0.0000531
learning_rate_init: 0.0000295
batch_size: 64
iterations spent: 200
time spent: 117.8
accuracy: 0.8820

#exp: 18
hidden_layer_sizes: (79, 38, 9)
alpha: 0.0000034
learning_rate_init: 0.0000145
batch_size: 64
iterations spent: 200
time spent: 98.4
accuracy: 0.8864

#exp: 19
hidden_layer_sizes: (60, 31, 31)
alpha: 0.0001626
learning_rate_init: 0.0000374
batch_size: 32
iterations spent: 200
time spent: 179.7
accuracy: 0.8737

#exp: 20
hidden_layer_sizes: (63, 16, 33)
alpha: 0.0000002
learning_rate_init: 0.0004308
batch_size: 256
iterations spent: 175
time spent: 36.9
accuracy: 0.8526

#exp: 21
hidden_layer_sizes: (80, 31, 3)
alpha: 0.0013477
learning_rate_init: 0.0023703
batch_size: 256
iterations spent: 53
time spent: 12.8
accuracy: 0.8336

#exp: 22
hidden_layer_sizes: (80, 3, 13)
alpha: 0.0017588
learning_rate_init: 0.0000449
batch_size: 512
iterations spent: 171
time spent: 31.8
accuracy: 0.8897

#exp: 23
hidden_layer_sizes: (48, 41, 40)
alpha: 0.0000035
learning_rate_init: 0.0014939
batch_size: 256
iterations spent: 85
time spent: 22.5
accuracy: 0.8302

#exp: 24
hidden_layer_sizes: (74, 42, 27)
alpha: 0.0000066
learning_rate_init: 0.0018809
batch_size: 128
iterations spent: 55
time spent: 21.5
accuracy: 0.8469

#exp: 25
hidden_layer_sizes: (21, 8, 4)
alpha: 0.0009806
learning_rate_init: 0.0002189
batch_size: 256
iterations spent: 200
time spent: 27.1
accuracy: 0.8884

#exp: 26
hidden_layer_sizes: (46, 15, 16)
alpha: 0.0008740
learning_rate_init: 0.0003553
batch_size: 512
iterations spent: 200
time spent: 31.8
accuracy: 0.8727

#exp: 27
hidden_layer_sizes: (33, 23, 36)
alpha: 0.0000833
learning_rate_init: 0.0001701
batch_size: 256
iterations spent: 200
time spent: 41.2
accuracy: 0.8780

#exp: 28
hidden_layer_sizes: (48, 15, 39)
alpha: 0.0000002
learning_rate_init: 0.0001162
batch_size: 64
iterations spent: 200
time spent: 99.4
accuracy: 0.8707

#exp: 29
hidden_layer_sizes: (49, 34, 21)
alpha: 0.0031432
learning_rate_init: 0.0001608
batch_size: 1024
iterations spent: 200
time spent: 28.7
accuracy: 0.8830

#exp: 30
hidden_layer_sizes: (25, 14, 25)
alpha: 0.0000577
learning_rate_init: 0.0002605
batch_size: 256
iterations spent: 188
time spent: 29.8
accuracy: 0.8747

#exp: 31
hidden_layer_sizes: (25, 49, 12)
alpha: 0.0003577
learning_rate_init: 0.0001448
batch_size: 64
iterations spent: 200
time spent: 113.9
accuracy: 0.8750

#exp: 32
hidden_layer_sizes: (82, 8, 15)
alpha: 0.0003541
learning_rate_init: 0.0005335
batch_size: 128
iterations spent: 129
time spent: 43.1
accuracy: 0.8593

#exp: 33
hidden_layer_sizes: (17, 17, 21)
alpha: 0.0000409
learning_rate_init: 0.0003505
batch_size: 64
iterations spent: 167
time spent: 103.1
accuracy: 0.8753

#exp: 34
hidden_layer_sizes: (40, 2, 32)
alpha: 0.0000001
learning_rate_init: 0.0001159
batch_size: 64
iterations spent: 200
time spent: 95.5
accuracy: 0.8737

#exp: 35
hidden_layer_sizes: (29, 38, 9)
alpha: 0.0000003
learning_rate_init: 0.0000132
batch_size: 512
iterations spent: 125
time spent: 15.7
accuracy: 0.8907

#exp: 36
hidden_layer_sizes: (23, 10, 25)
alpha: 0.0000007
learning_rate_init: 0.0000376
batch_size: 1024
iterations spent: 193
time spent: 17.8
accuracy: 0.8907

#exp: 37
hidden_layer_sizes: (16, 12, 10)
alpha: 0.0000014
learning_rate_init: 0.0000362
batch_size: 128
iterations spent: 144
time spent: 29.8
accuracy: 0.8897

#exp: 38
hidden_layer_sizes: (74, 13, 23)
alpha: 0.0002488
learning_rate_init: 0.0010279
batch_size: 32
iterations spent: 91
time spent: 97.3
accuracy: 0.8239

#exp: 39
hidden_layer_sizes: (75, 23, 14)
alpha: 0.0010733
learning_rate_init: 0.0001900
batch_size: 512
iterations spent: 200
time spent: 39.5
accuracy: 0.8807

#exp: 40
hidden_layer_sizes: (17, 8, 21)
alpha: 0.0002279
learning_rate_init: 0.0011829
batch_size: 512
iterations spent: 110
time spent: 13.0
accuracy: 0.8840

#exp: 41
hidden_layer_sizes: (80, 50, 7)
alpha: 0.0001199
learning_rate_init: 0.0002655
batch_size: 64
iterations spent: 158
time spent: 123.5
accuracy: 0.8082

#exp: 42
hidden_layer_sizes: (20, 43, 31)
alpha: 0.0000017
learning_rate_init: 0.0000130
batch_size: 256
iterations spent: 130
time spent: 27.2
accuracy: 0.8907

#exp: 43
hidden_layer_sizes: (42, 50, 16)
alpha: 0.0000012
learning_rate_init: 0.0002062
batch_size: 512
iterations spent: 200
time spent: 37.7
accuracy: 0.8730

#exp: 44
hidden_layer_sizes: (16, 16, 26)
alpha: 0.0096403
learning_rate_init: 0.0001768
batch_size: 64
iterations spent: 116
time spent: 60.6
accuracy: 0.8890

#exp: 45
hidden_layer_sizes: (98, 49, 21)
alpha: 0.0000007
learning_rate_init: 0.0001805
batch_size: 64
iterations spent: 178
time spent: 132.4
accuracy: 0.8285

#exp: 46
hidden_layer_sizes: (59, 34, 7)
alpha: 0.0000096
learning_rate_init: 0.0005535
batch_size: 256
iterations spent: 156
time spent: 37.0
accuracy: 0.8382

#exp: 47
hidden_layer_sizes: (83, 23, 14)
alpha: 0.0000685
learning_rate_init: 0.0020512
batch_size: 32
iterations spent: 52
time spent: 55.6
accuracy: 0.8389

#exp: 48
hidden_layer_sizes: (45, 42, 26)
alpha: 0.0049162
learning_rate_init: 0.0004934
batch_size: 32
iterations spent: 86
time spent: 167.9
accuracy: 0.8573

#exp: 49
hidden_layer_sizes: (31, 18, 3)
alpha: 0.0000050
learning_rate_init: 0.0066063
batch_size: 256
iterations spent: 58
time spent: 12.2
accuracy: 0.8757

#exp: 50
hidden_layer_sizes: (16, 36, 9)
alpha: 0.0000655
learning_rate_init: 0.0001810
batch_size: 32
iterations spent: 186
time spent: 154.6
accuracy: 0.8787

#exp: 51
hidden_layer_sizes: (35, 21, 10)
alpha: 0.0011301
learning_rate_init: 0.0001148
batch_size: 32
iterations spent: 200
time spent: 212.1
accuracy: 0.8697

#exp: 52
hidden_layer_sizes: (86, 10, 18)
alpha: 0.0004763
learning_rate_init: 0.0000231
batch_size: 64
iterations spent: 200
time spent: 131.4
accuracy: 0.8890

#exp: 53
hidden_layer_sizes: (53, 50, 40)
alpha: 0.0000012
learning_rate_init: 0.0060013
batch_size: 1024
iterations spent: 76
time spent: 16.9
accuracy: 0.8239

#exp: 54
hidden_layer_sizes: (30, 34, 18)
alpha: 0.0000001
learning_rate_init: 0.0000189
batch_size: 64
iterations spent: 146
time spent: 78.0
accuracy: 0.8900

#exp: 55
hidden_layer_sizes: (87, 41, 39)
alpha: 0.0001039
learning_rate_init: 0.0007418
batch_size: 512

iterations spent: 122
time spent: 37.8
accuracy: 0.8436

#exp: 56
hidden_layer_sizes: (47, 3, 21)
alpha: 0.0000040
learning_rate_init: 0.0003543
batch_size: 256
iterations spent: 166
time spent: 38.2
accuracy: 0.8800

#exp: 57
hidden_layer_sizes: (99, 31, 27)
alpha: 0.0000012
learning_rate_init: 0.0078539
batch_size: 1024
iterations spent: 50
time spent: 12.5
accuracy: 0.8539

#exp: 58
hidden_layer_sizes: (56, 3, 25)
alpha: 0.0008588
learning_rate_init: 0.0011856
batch_size: 64
iterations spent: 74
time spent: 40.4
accuracy: 0.8683

#exp: 59
hidden_layer_sizes: (59, 9, 23)
alpha: 0.0000016
learning_rate_init: 0.0000440
batch_size: 512
iterations spent: 200
time spent: 40.7
accuracy: 0.8900

#exp: 60
hidden_layer_sizes: (34, 33, 33)
alpha: 0.0000192
learning_rate_init: 0.0000133
batch_size: 512
iterations spent: 156
time spent: 30.5
accuracy: 0.8907

#exp: 61
hidden_layer_sizes: (39, 34, 15)
alpha: 0.0024819
learning_rate_init: 0.0000338
batch_size: 64
iterations spent: 200
time spent: 111.0
accuracy: 0.8874

#exp: 62
hidden_layer_sizes: (97, 18, 33)
alpha: 0.0008418
learning_rate_init: 0.0000106
batch_size: 256
iterations spent: 124
time spent: 44.2
accuracy: 0.8907

#exp: 63
hidden_layer_sizes: (84, 37, 28)
alpha: 0.0000052
learning_rate_init: 0.0000283
batch_size: 1024
iterations spent: 146
time spent: 34.2
accuracy: 0.8907

#exp: 64
hidden_layer_sizes: (43, 42, 26)
alpha: 0.0001750
learning_rate_init: 0.0000470
batch_size: 128
iterations spent: 200
time spent: 80.2
accuracy: 0.8877

#exp: 65
hidden_layer_sizes: (84, 25, 35)
alpha: 0.0047796
learning_rate_init: 0.0000113
batch_size: 128
iterations spent: 200
time spent: 95.2
accuracy: 0.8907

#exp: 66
hidden_layer_sizes: (93, 32, 8)
alpha: 0.0022645
learning_rate_init: 0.0019447
batch_size: 64
iterations spent: 58
time spent: 50.3
accuracy: 0.8316

#exp: 67
hidden_layer_sizes: (20, 30, 27)
alpha: 0.0000846
learning_rate_init: 0.0014307
batch_size: 256
iterations spent: 102
time spent: 22.0
accuracy: 0.8703

#exp: 68
hidden_layer_sizes: (15, 28, 14)
alpha: 0.0000026
learning_rate_init: 0.0000377
batch_size: 256
iterations spent: 142
time spent: 25.8
accuracy: 0.8907

#exp: 69
hidden_layer_sizes: (37, 50, 11)
alpha: 0.0009429
learning_rate_init: 0.0004756
batch_size: 128
iterations spent: 150
time spent: 60.2
accuracy: 0.8763

#exp: 70
hidden_layer_sizes: (86, 39, 4)
alpha: 0.0000008
learning_rate_init: 0.0015758
batch_size: 512
iterations spent: 102
time spent: 26.5
accuracy: 0.8239

#exp: 71
hidden_layer_sizes: (86, 16, 13)
alpha: 0.0000060
learning_rate_init: 0.0022206
batch_size: 64
iterations spent: 67
time spent: 43.3
accuracy: 0.8533

#exp: 72
hidden_layer_sizes: (2, 49, 2)
alpha: 0.0001057
learning_rate_init: 0.0017591
batch_size: 256
iterations spent: 10
time spent: 1.7
accuracy: 0.8907

#exp: 73
hidden_layer_sizes: (37, 6, 7)
alpha: 0.0000013
learning_rate_init: 0.0073273
batch_size: 64
iterations spent: 56
time spent: 26.0
accuracy: 0.8606

#exp: 74
hidden_layer_sizes: (62, 49, 37)
alpha: 0.0000175
learning_rate_init: 0.0006068
batch_size: 512
iterations spent: 133
time spent: 35.3
accuracy: 0.8382

#exp: 75
hidden_layer_sizes: (62, 12, 7)
alpha: 0.0008112
learning_rate_init: 0.0005830
batch_size: 32
iterations spent: 137
time spent: 147.8
accuracy: 0.8459

#exp: 76
hidden_layer_sizes: (73, 21, 2)
alpha: 0.0007254
learning_rate_init: 0.0021645
batch_size: 1024
iterations spent: 97
time spent: 18.2
accuracy: 0.7894

#exp: 77
hidden_layer_sizes: (66, 39, 10)
alpha: 0.0000050
learning_rate_init: 0.0000727
batch_size: 256
iterations spent: 200
time spent: 63.6
accuracy: 0.8847

#exp: 78
hidden_layer_sizes: (61, 39, 36)
alpha: 0.0005810
learning_rate_init: 0.0007249
batch_size: 128
iterations spent: 95
time spent: 54.8
accuracy: 0.8239

#exp: 79
hidden_layer_sizes: (72, 22, 3)
alpha: 0.0000195
learning_rate_init: 0.0000192
batch_size: 64
iterations spent: 200
time spent: 122.8
accuracy: 0.8907

#exp: 80
hidden_layer_sizes: (10, 16, 17)
alpha: 0.0000248
learning_rate_init: 0.0000444
batch_size: 32
iterations spent: 108
time spent: 67.6
accuracy: 0.8880

#exp: 81
hidden_layer_sizes: (45, 46, 33)
alpha: 0.0002472
learning_rate_init: 0.0011658
batch_size: 256
iterations spent: 99
time spent: 30.3
accuracy: 0.8416

#exp: 82
hidden_layer_sizes: (73, 12, 8)
alpha: 0.0000004
learning_rate_init: 0.0000835
batch_size: 128
iterations spent: 200
time spent: 72.5
accuracy: 0.8840

#exp: 83
hidden_layer_sizes: (92, 8, 11)
alpha: 0.0000001
learning_rate_init: 0.0036792
batch_size: 1024
iterations spent: 82
time spent: 16.5
accuracy: 0.8519

#exp: 84
hidden_layer_sizes: (86, 28, 38)
alpha: 0.0002892
learning_rate_init: 0.0002115
batch_size: 512
iterations spent: 200
time spent: 57.5
accuracy: 0.8623

#exp: 85
hidden_layer_sizes: (94, 33, 4)
alpha: 0.0011909
learning_rate_init: 0.0010246
batch_size: 32
iterations spent: 103
time spent: 223.0
accuracy: 0.8372

#exp: 86
hidden_layer_sizes: (45, 5, 39)
alpha: 0.0007803
learning_rate_init: 0.0000123
batch_size: 32
iterations spent: 152
time spent: 151.7
accuracy: 0.8897

#exp: 87
hidden_layer_sizes: (65, 14, 10)
alpha: 0.0000167
learning_rate_init: 0.0001831
batch_size: 1024
iterations spent: 200
time spent: 35.3
accuracy: 0.8870

#exp: 88
hidden_layer_sizes: (20, 13, 39)
alpha: 0.0001506
learning_rate_init: 0.0020336
batch_size: 512
iterations spent: 73
time spent: 12.1
accuracy: 0.8676

#exp: 89
hidden_layer_sizes: (33, 29, 13)
alpha: 0.0007846
learning_rate_init: 0.0064457
batch_size: 64
iterations spent: 58
time spent: 38.4
accuracy: 0.8710

#exp: 90
hidden_layer_sizes: (96, 41, 16)
alpha: 0.0000304
learning_rate_init: 0.0000123
batch_size: 64
iterations spent: 200
time spent: 158.2
accuracy: 0.8884

#exp: 91
hidden_layer_sizes: (97, 19, 36)
alpha: 0.0003523
learning_rate_init: 0.0002061
batch_size: 256
iterations spent: 200
time spent: 75.4
accuracy: 0.8399

#exp: 92
hidden_layer_sizes: (83, 15, 2)
alpha: 0.0017766
learning_rate_init: 0.0002684
batch_size: 256
iterations spent: 200
time spent: 62.2
accuracy: 0.8529

#exp: 93
hidden_layer_sizes: (80, 9, 21)
alpha: 0.0000024
learning_rate_init: 0.0004578
batch_size: 32
iterations spent: 120
time spent: 150.9
accuracy: 0.8356

#exp: 94
hidden_layer_sizes: (23, 26, 14)
alpha: 0.0000050
learning_rate_init: 0.0000994
batch_size: 128
iterations spent: 200
time spent: 71.1
accuracy: 0.8874

#exp: 95
hidden_layer_sizes: (5, 47, 9)
alpha: 0.0000304
learning_rate_init: 0.0000153
batch_size: 1024
iterations spent: 116
time spent: 13.5
accuracy: 0.8907

#exp: 96
hidden_layer_sizes: (57, 8, 40)
alpha: 0.0000004
learning_rate_init: 0.0008840
batch_size: 128
iterations spent: 119
time spent: 44.9
accuracy: 0.8429

#exp: 97
hidden_layer_sizes: (56, 43, 37)
alpha: 0.0000285
learning_rate_init: 0.0055667
batch_size: 512
iterations spent: 55
time spent: 14.3
accuracy: 0.8399

#exp: 98
hidden_layer_sizes: (7, 49, 32)
alpha: 0.0000031
learning_rate_init: 0.0009001
batch_size: 512
iterations spent: 79
time spent: 13.4
accuracy: 0.8877

#exp: 99
hidden_layer_sizes: (16, 21, 32)
alpha: 0.0051788
learning_rate_init: 0.0073468
batch_size: 1024
iterations spent: 65
time spent: 8.8
accuracy: 0.8747

#exp: 100
hidden_layer_sizes: (47, 34, 17)
alpha: 0.0027847
learning_rate_init: 0.0000663
batch_size: 256
iterations spent: 200
time spent: 57.8
accuracy: 0.8884